### ISSUE TITLE
Data migration use-case - enhancement to extract_file?

### ISSUE THREAD

**Issue by wattdave** [Autodesk/aomi#107]
We have a situation where it'd be really handy to have a tool that can say:

"Read the contents of this mount point, and write the results to a .yaml or other massageable, human-readable file"

The idea being to have a simpler way to migrate the contents of a mount point from one location to another.

**Comment by otakup0pe** [comment]
Do you think that https://github.com/Autodesk/aomi/issues/92 will cover the export aspect of this use case? For generic moving data around, I'd recommend https://github.com/starkandwayne/safe

**Comment by wattdave** [comment]
Yes, seems like it would.

**Comment by otakup0pe** [comment]
Closing in favor of https://github.com/Autodesk/aomi/issues/92
