### ISSUE TITLE
Creating a new mount point should be a conscious act

### ISSUE THREAD

**Issue by wattdave** [Autodesk/aomi#110]
A suggestion: add a flag to `aomi seed` to explicitly allow creation of new mount points. Otherwise, if the flag is not specified, and the mount point does not exist, fail the call. This would allow newbie users to not inadvertently create new mount points without realizing what they're doing.

**Comment by otakup0pe** [comment]
The first part is already [supported](https://autodesk.github.io/aomi/secretfile#mountpoints). I could be easily convinced to have the "create generic on missing mount" functionality deprecated...
