### ISSUE TITLE
Support Token Credential Backend Roles management

### ISSUE THREAD

**Issue by skovorodkin** [Autodesk/aomi#133]
Vault 0.5.2 [introduced](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#052-march-16th-2016) Token Credential Backend Roles:

> Roles can now be created in the token credential backend that allow modifying token behavior in ways that are not otherwise exposed or easily delegated. This allows creating tokens with a fixed set (or subset) of policies (rather than a subset of the calling token's), periodic tokens with a fixed TTL but no expiration, specified prefixes, and orphans.

Docs are here https://www.vaultproject.io/docs/auth/token.html#auth-token-roles-role_name-

**Comment by otakup0pe** [comment]
We would welcome a PR for this functionality, although it is not on our near term roadmap.

**Comment by skovorodkin** [comment]
I considered Token Roles, but decided to use AppRoles after all, so I don't need Token Roles anymore. Should we close this issue then?

**Comment by mjuarez** [comment]
Token roles appear to be one of the recommended ways of Vault integration with Nomad: https://www.nomadproject.io/docs/vault-integration/index.html
