### ISSUE TITLE
Change auth from a resource to a mount

### ISSUE THREAD

**Issue by ericfode** [Autodesk/aomi#140]
https://github.com/Autodesk/aomi/blob/d385ba14ac3ac499130ab46d037c186865489b82/aomi/model/resource.py#L264-L268

I think this will be required to have multiple auth backends of the same kind.

**Comment by otakup0pe** [comment]
Not actually required for multiple auth backends... Adding #101  (mountpoint tuning) has shown we _might_ want to distinguish more clearly between backends and resources in terms of the overall context. Dunno if I'll address it in next PR or punt...
