### ISSUE TITLE
All links at the begining of operations.md broken

### ISSUE THREAD

**Issue by ericfode** [Autodesk/aomi#141]
If you are reading it in the repo... Maybe move the doc site to it's own repo so it's not expected to work...

The relevent text is pasted.

diff will display the steps required to have the Vault server reflect what is defined in the Secretfile.
seed will write what is defined in the Secretfile to the Vault server.
freeze will save the secrets defined in the Secretfile to an "icefile".
thaw will extract secrets defined in the Secretfile from a previously frozen "icefile".
export readable secrets from a Vault server as defined in the Secretfile.

**Comment by otakup0pe** [comment]
When you say "in the repo" do you mean locally?

**Comment by ericfode** [comment]
no i mean when i open them up in github. not github pages. They should probably be hidden if they don't work in both places?

**Comment by otakup0pe** [comment]
So the docs are templates, not meant for direct use. I guess we could have a README.md in the docs page explaining that. Pretty sure we can do this and have it not get included in a jekyll run.

**Comment by otakup0pe** [comment]
Slipped this change into https://github.com/Autodesk/aomi/pull/150 as visible [here](https://github.com/Autodesk/aomi/blob/master/docs/README.md). The README itself shouldn't end up on the page itself either...
