### ISSUE TITLE
non terrible error handling

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#26]
We should report friendly errors for the following
- vault permission/server issues
- bad yaml
- unix permission drama
- files not found

Errors should bubble up via exceptions.

**Comment by shaiguitar** [comment]
👍

**Comment by otakup0pe** [comment]
To be fair, until we have better passing of exceptions (rather than gratuitous use of the `problems` helper) we can't have decent unit tests.

**Comment by otakup0pe** [comment]
From a conversation with @kdauler

```
i was envisioning `error.py` that has exceptions declared (along with nice string representations)
then instead of calling `problems` all over the place, we throw exceptions
then in `cli.py` we have something which catches exceptions and prints messages with context
```

**Comment by otakup0pe** [comment]
Fixed in https://github.com/Autodesk/aomi/commit/6ed5c4b1739e5be184d028d1d8c752835c53b64c

Exceptions are caught and handled in a bit of a nicer fashion. All the references to `aomi.helpers.problems` have been replaced by a bespoke exception and some consistent logging.
