### ISSUE TITLE
Source paths like

### ISSUE THREAD

**Issue by ericfode** [Autodesk/aomi#3]
'~/.chef/dockersec-validator'
end up getting expaned as
$(pwd)/~/.chef/dockersec-validator

and then it can't find the file

**Comment by otakup0pe** [comment]
Needs more context. Is this during a `seed` ?

**Comment by ericfode** [comment]
Yes it was during a seed. I was trying to point it to a path where the file currently lived. I did not understand the assumtoion that all of your secrets would be in a subdirectory of your current path.

**Comment by otakup0pe** [comment]
Fixed in https://github.com/Autodesk/aomi/tree/0.3.1
