### ISSUE TITLE
Enable LDAP support

### ISSUE THREAD

**Issue by kdauler** [Autodesk/aomi#38]
Add ldap config support for enabling new ldap mountpoints. 

Note this will include the following

* Binding auth mountpoints to LDAP domains
* Make sure that DUO works with LDAP as expected
* We only need to support ["User Principal"](https://www.vaultproject.io/docs/auth/ldap.html#binding-user-principal-name-ad-) binding

Bonus : this means that the LDAP endpoint won't actually need any secrets, so that is cool.

**Comment by otakup0pe** [comment]
![](https://media.giphy.com/media/ujbSNTuJxQ1So/giphy.gif)

Note the `ldap_auth` resource will treat the `bindpass` and `certificate` as a secret. Everything else is meta.
