### ISSUE TITLE
Missing install instructions

### ISSUE THREAD

**Issue by aaronaddleman** [Autodesk/aomi#43]
It would be helpful to have some install instructions. Trying to resolve the problem of installing aomi and running into the following error on centos7:

```
# /opt/rh/python27/root/usr/bin/pip install aomi
Collecting aomi
  Using cached aomi-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-build-4OIPlc/aomi/version is missing
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4OIPlc/aomi/
# 
```

**Comment by otakup0pe** [comment]
This was a side effect of moving the `version` file into the `aomi` subdirectory during packaging so it could be accessible during the runtime. It now shows up in `aomi help`. Is fixed in 0.9.2.
