### ISSUE TITLE
plan/diff action

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#70]
This would show a colordiff of the results for running `aomi seed` on Vault. It would also calculate the expected permissions necessary to complete the `seed` action. This action would necessitate read permissions on contextual vault paths, and some information will never be diffable (i.e. aws root creds)

**Comment by ericfode** [comment]
```
conceptually 
diff: PredictedStateOfVault -> ActualStateOfVault -> TreeDiff
plan: TreeDiff -> VaultConnection -> [Changes]
seed: VaultConnection -> Changes -> Sideeffect Vault
```

**Comment by otakup0pe** [comment]
@ericfode I've been thinking about this more as I gear up to handle the refactoring needed... For the `plan` output, could we consider a fully rendered `Secretfile` with only the expected changes to vault as sufficient ? I think that could then feed easily into the logic of `seed`.
