### ISSUE TITLE
Validate tests under Windows 

### ISSUE THREAD

**Issue by wattdave** [Autodesk/aomi#73]
Update the tests so that they use Windows paths when running on Windows - tests/test_validation.py needs some use of os.path.join() to make it less centered on '/' in path names.

The broader question is: how would we validate that the tests pass on Windows, ideally integrated as part of the pull request and commit process?

**Comment by wattdave** [comment]
https://www.appveyor.com/ seems to be a possible option. Doing research...

**Comment by wattdave** [comment]
Also: http://docs.tea-ci.org/usage/overview/

**Comment by wattdave** [comment]
Someone's experience using Appveyor - looks like some tire-kicking there would be in order...

https://www.software.ac.uk/blog/2016-11-11-appveyor-travis-ci-windows

**Comment by otakup0pe** [comment]
Appveyor seems like the best contender... https://github.com/ogrisel/python-appveyor-demo

**Comment by otakup0pe** [comment]
Works as intended under WSL, unlikely to make work under stock Windows.
